package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Canvas = 0;
  public static final int Circle = 1;
  public static final int Color = 2;
  public static final int Shape = 3;
  public static final int Square = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x40d6109e654b4e3dL, 0x81a4dbf8ab02510eL);
    builder.put(0x7b93775da96c8b1dL, Canvas);
    builder.put(0x7b93775da96c8b07L, Circle);
    builder.put(0x7b93775da96e20d9L, Color);
    builder.put(0x7b93775da96c8b04L, Shape);
    builder.put(0x7b93775da96c8b13L, Square);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
