package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptCircle = createDescriptorForCircle();
  /*package*/ final ConceptDescriptor myConceptColor = createDescriptorForColor();
  /*package*/ final ConceptDescriptor myConceptShape = createDescriptorForShape();
  /*package*/ final ConceptDescriptor myConceptSquare = createDescriptorForSquare();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCanvas, myConceptCircle, myConceptColor, myConceptShape, myConceptSquare);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Canvas:
        return myConceptCanvas;
      case LanguageConceptSwitch.Circle:
        return myConceptCircle;
      case LanguageConceptSwitch.Color:
        return myConceptColor;
      case LanguageConceptSwitch.Shape:
        return myConceptShape;
      case LanguageConceptSwitch.Square:
        return myConceptSquare;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCanvas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Canvas", 0x40d6109e654b4e3dL, 0x81a4dbf8ab02510eL, 0x7b93775da96c8b1dL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:3163a4e0-142d-4084-aecf-3969f6fe943b(Shapes.structure)/8904592132399729437");
    b.version(2);
    b.aggregate("shapes", 0x7b93775da96c8b26L).target(0x40d6109e654b4e3dL, 0x81a4dbf8ab02510eL, 0x7b93775da96c8b04L).optional(true).ordered(true).multiple(true).origin("8904592132399729446").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCircle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Circle", 0x40d6109e654b4e3dL, 0x81a4dbf8ab02510eL, 0x7b93775da96c8b07L);
    b.class_(false, false, false);
    b.super_("Shapes.structure.Shape", 0x40d6109e654b4e3dL, 0x81a4dbf8ab02510eL, 0x7b93775da96c8b04L);
    b.origin("r:3163a4e0-142d-4084-aecf-3969f6fe943b(Shapes.structure)/8904592132399729415");
    b.version(2);
    b.property("x", 0x7b93775da96c8b0aL).type(PrimitiveTypeId.INTEGER).origin("8904592132399729418").done();
    b.property("y", 0x7b93775da96c8b0cL).type(PrimitiveTypeId.INTEGER).origin("8904592132399729420").done();
    b.property("radius", 0x7b93775da96c8b0fL).type(PrimitiveTypeId.INTEGER).origin("8904592132399729423").done();
    b.alias("circle");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Color", 0x40d6109e654b4e3dL, 0x81a4dbf8ab02510eL, 0x7b93775da96e20d9L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:3163a4e0-142d-4084-aecf-3969f6fe943b(Shapes.structure)/8904592132399833305");
    b.version(2);
    b.alias("color");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShape() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Shape", 0x40d6109e654b4e3dL, 0x81a4dbf8ab02510eL, 0x7b93775da96c8b04L);
    b.class_(false, true, false);
    b.origin("r:3163a4e0-142d-4084-aecf-3969f6fe943b(Shapes.structure)/8904592132399729412");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSquare() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Square", 0x40d6109e654b4e3dL, 0x81a4dbf8ab02510eL, 0x7b93775da96c8b13L);
    b.class_(false, false, false);
    b.super_("Shapes.structure.Shape", 0x40d6109e654b4e3dL, 0x81a4dbf8ab02510eL, 0x7b93775da96c8b04L);
    b.origin("r:3163a4e0-142d-4084-aecf-3969f6fe943b(Shapes.structure)/8904592132399729427");
    b.version(2);
    b.property("upperLeftX", 0x7b93775da96c8b14L).type(PrimitiveTypeId.INTEGER).origin("8904592132399729428").done();
    b.property("upperLeftY", 0x7b93775da96c8b16L).type(PrimitiveTypeId.INTEGER).origin("8904592132399729430").done();
    b.property("size", 0x7b93775da96c8b19L).type(PrimitiveTypeId.INTEGER).origin("8904592132399729433").done();
    b.alias("square");
    return b.create();
  }
}
